language: ruby
rvm:
   - 2.2.5
matrix:
env:
   - DEBUG=1
   - COVERAGE=1

before_install:
  - sudo apt-get update -qq
install:
  - gem --version
  - ruby --version
  - gem install coveralls
  - gem install bashcov
  - sudo gem update --system
  - bundle install
  - sh -e misc/ci-setup.sh
#  - export PATH="$PATH:$PWD"
script:
  - sh -e misc/ci-runtest.sh
