language: ruby
rvm:
   - 2.2.5
matrix:
env:
   - COVERAGE=1 DEBUG=1 
   - COVERAGE=1
   - COVERAGE=0

before_install:
  - sudo apt-get update -qq
install:
  - gem install coveralls
  - gem install bashcov
  - sudo gem update --system
  - misc/ci-setup.sh
#  - export PATH="$PATH:$PWD"
script:
  - misc/ci-runtest.sh
