language: ruby
rvm:
   - 2.2.5
matrix:
env:
   - COVERAGE=1 DEBUG=1 
#   - COVERAGE=1
#   - COVERAGE=0

before_install:
  - sudo apt-get update -qq
install:
  - which gem
  - sudo gem install  coveralls
  - sudo gem install  bashcov
  - bundle install
  - misc/ci-setup.sh
#  - export PATH="$PATH:$PWD"
script:
  - misc/ci-runtest.sh
