#language: shell
dist: trusty
language: ruby
rvm:
   - 2.4.0

matrix:
  include:
      - env: COVERAGE=1 
cache:
  directories:
    - $HOME/.m2/repository

before_install:
  - sudo apt-get update -qq

install:
  - sudo gem install -V bashcov
  - sudo gem install coveralls
  - sudo gem contents bashcov
  - sh -e misc/ci-setup.sh

script:
  - sh -e misc/ci-runtest.sh
