language: ruby
rvm:
   - 2.2.5
matrix:
env:
   - COVERAGE=1 DEBUG=1 DESPF_NS="8.8.8.8 8.8.4.4"
   - COVERAGE=1

before_install:
  - sudo apt-get update -qq
install:
  - gem install coveralls
  - gem install bashcov
  - sudo gem update --system
  - bundle install
  - sh -e misc/ci-setup.sh
#  - export PATH="$PATH:$PWD"
script:
  - sh -e misc/ci-runtest.sh
