language: ruby
rvm:
   - 2.2.5
matrix:
env:
   - COVERAGE=1 DEBUG=1 
#   - COVERAGE=1
#   - COVERAGE=0

before_install:
  - sudo apt-get update -qq
install:
  - which gem
  - gem install  coveralls -n ./bin
  - gem install  bashcov -n ./bin
  - misc/ci-setup.sh
#  - export PATH="$PATH:$PWD"
script:
  - misc/ci-runtest.sh
