language: ruby
rvm:
   - 2.2.5
matrix:
env:
   - COVERAGE=1 DEBUG=1 
#   - COVERAGE=1
#   - COVERAGE=0

before_install:
  - sudo apt-get update -qq
install:
  - which gem
  - sudo -E /home/travis/.rvm/rubies/ruby-2.2.5/bin/gem install  coveralls -n /usr/local/bin
  - sudo -E /home/travis/.rvm/rubies/ruby-2.2.5/bin/gem install  bashcov -n /usr/local/bin
  - gem regenerate_binstubs
  - sudo -E /home/travis/.rvm/rubies/ruby-2.2.5/bin/gem install  --user-install executable-hooks
  - misc/ci-setup.sh
  - find .
#  - export PATH="$PATH:$PWD"
script:
  - misc/ci-runtest.sh
