language: ruby
rvm:
   - 2.2.5
matrix:
env:
#   - COVERAGE=1 DEBUG=1 
   - COVERAGE=1
   - COVERAGE=0

before_install:
  - sudo apt-get update -qq
install:
  - which gem
  - gem install  coveralls 
  - gem install  bashcov 
  - gem regenerate_binstubs
  - export PATH="$PATH:$PWD:$GEM_PATH:/home/travis/.rvm/gems/ruby-2.2.5/wrappers"
  - misc/ci-setup.sh
script:
  -  misc/ci-runtest.sh || true
