language: ruby
rvm:
   - 2.2.5
matrix:
env:
   - COVERAGE=1 DEBUG=1 
#   - COVERAGE=1
#   - COVERAGE=0

before_install:
  - sudo apt-get update -qq
install:
  - which gem
  - sudo -E $GEM_HOME/bin/gem install  coveralls -n /usr/local/bin
  - sudo -E $GEM_HOME/bin/gem install  bashcov -n /usr/local/bin
  - misc/ci-setup.sh
  - find .
#  - export PATH="$PATH:$PWD"
script:
  - misc/ci-runtest.sh
