#language: shell

sudo: false


matrix:
  include:
#      - env: COVERAGE=0 
      - env: COVERAGE=1 
cache:
  directories:
    - $HOME/.m2/repository

before_install:
  - sudo apt-get update -qq

install:
  - gem install bashcov
  - gem install coveralls
  - sh -e misc/ci-setup.sh

script:
  - sh -e misc/ci-runtest.sh
